# Generated by Django 3.1.7 on 2021-03-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbs_for_video',
            field=models.ImageField(default='', upload_to='tutorial_thumbs'),
        ),
    ]
